Updated readme
GSG-CF04/COVIDtracker pull request #33
Opened 2021-11-29 15:09 UTC by samahjamie

please check this draft, and try to put your ideas about the solution and problem. @techhana2014 
@Ibrahimnabeel9  kindly add the desktop responsive image.

2021-11-29 17:40 UTC, yazan05 reviewed
Make :"(( Project Name
Links
Problem 
etc .. )) a hyperlink 

Decide which way you will use to navigate between pages , to edit button design in User Journey >> **Next** or **Swipe**

2021-11-29 17:58 UTC, Ibrahimnabeel9 approved these changes

2021-11-30 05:36 UTC, techhana2014 requested changes
there is some changes in readme

2021-11-30 05:36 UTC, techhana2014 commented on README.md
> +* [Our figma design](https://)
where is figma link!

2021-11-30 05:36 UTC, techhana2014 commented on README.md
> +* Our API documentation: [1 2 3](https://)
and API links?

2021-11-30 05:36 UTC, techhana2014 commented on README.md
> +### **Problem:** <span id='about'></span>
here we should write about problems

2021-11-30 05:36 UTC, techhana2014 commented on README.md
> +### **Solution:** <span id='about'></span>
where is solutions samah

2021-11-30 05:36 UTC, techhana2014 commented on README.md
> +* You can visit our live website [Here](https://)
where is live link?

2021-12-05 09:06 UTC, closed without merging