Add current user country relates to ip location in statistics
GSG-CF04/COVIDtracker pull request #43
Opened 2021-12-03 17:27 UTC by techhana2014

time estimated : 4 hours
time taken : 4 hours

2021-12-03 17:58 UTC, Ibrahimnabeel9 approved these changes

2021-12-03 20:17 UTC, yazan05 approved these changes

2021-12-04 14:29 UTC, Ibrahim-Jarada requested changes

2021-12-04 14:29 UTC, Ibrahim-Jarada commented on statistics/statistics.js
> +        const response2 = await fetch(api2); // Get data from API country
Don't put your fetchs in series in a try catch
So when the API 1 fails the same as API 2 fails
while your application can run without the first api in the search mode

2021-12-04 20:43 UTC, Ibrahim-Jarada approved these changes

2021-12-04 20:44 UTC, merged