Add responsive and dark mood code in statistics page
GSG-CF04/COVIDtracker pull request #45
Opened 2021-12-04 22:14 UTC by techhana2014

Add responsive code in statistics page >> relates#22"
"create dark mood for statistics page >> relates#32"
time estimated : 4 hours
time taken: 4 hours

2021-12-04 22:32 UTC, yazan05 approved these changes

2021-12-04 23:43 UTC, Ibrahimnabeel9 approved these changes

2021-12-05 09:34 UTC, Ibrahim-Jarada requested changes
Put your dark mode button in a place that user can notice it better, and realize that its a button not an image

2021-12-05 09:34 UTC, Ibrahim-Jarada commented on statistics/statistics.css
> +background: var(--bg-c); /* FOR DARK THEME */
Alwasy add browser fall back and debugging fallback when you use `var()`
Check the links below
[Attach a Fallback value to a CSS Variable](https://www.freecodecamp.org/learn/responsive-web-design/basic-css/attach-a-fallback-value-to-a-css-variable)
[Improve Compatibility with Browser Fallbacks](https://www.freecodecamp.org/learn/responsive-web-design/basic-css/improve-compatibility-with-browser-fallbacks)

Note: Browser fallback much more important and it considered as enough its alone

2021-12-05 12:02 UTC, techhana2014 commented
Changes requested resolved

2021-12-05 12:24 UTC, Ibrahim-Jarada approved these changes

2021-12-05 14:03 UTC, merged