Update readme file
GSG-CF04/COVIDtracker pull request #46
Opened 2021-12-04 22:31 UTC by techhana2014

relates#31

2021-12-04 22:36 UTC, yazan05 approved these changes

2021-12-04 23:43 UTC, Ibrahimnabeel9 approved these changes

2021-12-05 07:22 UTC, Ibrahim-Jarada requested changes

2021-12-05 07:22 UTC, Ibrahim-Jarada commented on README.md
>  * As a user, you will be able to skip instructions every time you access the page.
Where is the search feature?

2021-12-05 09:00 UTC, techhana2014 commented
I resolve the request

2021-12-05 09:02 UTC, Ibrahim-Jarada approved these changes

2021-12-05 09:18 UTC, merged