Create index html page
GSG-CF04/COVIDtracker pull request #47
Opened 2021-12-04 23:42 UTC by Ibrahimnabeel9

Relates #3

2021-12-05 04:09 UTC, techhana2014 approved these changes

2021-12-05 07:59 UTC, yazan05 commented on index.html
> +    <div class="title">
remove div and add article

2021-12-05 08:00 UTC, yazan05 commented on index.html
> +    <div class="background">
replace div with figure

2021-12-05 08:01 UTC, yazan05 requested changes
<a class="start-btn" href='page1.html'>Countinue</a> >>>> edit href  : instructions.html

2021-12-06 15:44 UTC, Ibrahim-Jarada requested changes
Always use semantic HTML
Check this link [Semantic HTML](https://github.com/gazaskygeeks/Coding-Foundations-course/blob/master/coursebook/Week%2001/session-02/semantic.md)

2021-12-06 15:44 UTC, Ibrahim-Jarada commented on index.html
> +    </article>
After you enter the body It better to use `<section> ` not `<article> `

2021-12-06 15:44 UTC, Ibrahim-Jarada commented on index.html
> +    </section>
Use `<nav>` instead of `<section>` for your navigation  bar

2021-12-06 22:43 UTC, yazan05 approved these changes

2021-12-07 13:19 UTC, Ibrahim-Jarada approved these changes

2021-12-07 13:30 UTC, merged