Create style css page
GSG-CF04/COVIDtracker pull request #48
Opened 2021-12-05 00:14 UTC by Ibrahimnabeel9

Relates #4

2021-12-05 04:09 UTC, techhana2014 approved these changes

2021-12-05 09:11 UTC, Ibrahim-Jarada requested changes

2021-12-05 09:11 UTC, Ibrahim-Jarada commented on style.css
> +@import url("https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+KR:wght@400;500;700&display=swap");
Don't use `@import `in your stylesheet use its alternative `<link>` in HTML file `<head>`
It slows down your page and reduce accessibility and affects SEO

2021-12-06 15:45 UTC, Ibrahim-Jarada approved these changes

2021-12-06 20:00 UTC, yazan05 approved these changes

2021-12-07 03:33 UTC, merged